### ISSUE TITLE
Build script?

### ISSUE THREAD

**Issue by jsumners** [eliben/modlib#2]
What would a build script, e.g. a [Taskfile](https://taskfile.dev), look like for this project? Assuming one wants to clone the repo and build things locally instead of using `go install`, how does one go about that?

**Comment by eliben** [comment]
What's wrong with `go build`?

For a simple, pure-go project like this one, it's absolutely sufficient IMHO

**Comment by jsumners** [comment]
Does that build the binaries in `cmd/`? I am genuinely asking as someone relatively new to Go and unclear how a project structure such as this one should be built to accomplish building everything.

**Comment by eliben** [comment]
The users of the project get the binaries by running `go install ....` as specified in the README. You can also build a command locally with e.g. `go build ./cmd/modlib-client`, though this is rarely needed as you'll be using `go run` or `go test` most of the time.

For more specialized needs you can use any automation approach, like a shell script, makefile or what have you. This is very general and preference-based, so I'm not sure it's in scope for this template project

**Comment by jsumners** [comment]
I think it is part of understand how the project structure works. It isn't clear to someone who is new to this that `go build ./cmd/modlib-client` is the required command. If the goal is to teach people how to structure _and use_ a project that contains a module plus commands, then the final instructions are missing. As an example, I assume someone working in such a project wouldn't be expected to `go install <something>` in order to setup a debugger profile to debug a command while developing it.

**Comment by eliben** [comment]
I have added a note to the project's README about building binaries locally with `go build`. WDYT?

I don't think I'm going to get into build scripts here, since the spectrum of possibilities is so large and many projects get by without anything special (just using the `go` tool).

**Comment by jsumners** [comment]
Looks good to me. Thanks.
